### PR TITLE
Vcr workflow action debugging

### PR DESCRIPTION
**Pull request by igor-davidyuk**
This PR streamlines VCR cassette recording process.

TODO:
- [ ] Identify the affected components in a PR and only record cassettes for the related tests
- [ ] optional flow is to run failed integration tests in recording mode automatically

### CODE REVIEW

**Review by ljcornel — COMMENTED** [review]
The workflow looks good to me, could you clean up the comments a bit?

**Comment by igor-davidyuk** [comment]
> The workflow looks good to me, could you clean up the comments a bit?

I cleaned up the code!

There is one more thing - I had to use `virtualenv` for the environment management as conda failed to install the required packages for some reason. 
So the environment is created in the repo root, I am worried it could consume all the memory over time if not cleaned up. Do we remove the repo folder after tests on the runner machine?

**Comment by ljcornel** [comment]
I don't think the repo folder is removed completely, changes are pulled but that won't affect the .venv folder of course. Can't you remove it in a clean-up step that runs after the tests? With some check to make sure it doesn't fail if the folder doesn't exist for some reason

**Review by ljcornel — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
